// frontend/uml2code-frontend/src/components/stepper/StepperDot.jsx
import CheckMark from "../icons/Checkmark"

const StepperDot = ({ step, isActive, isCompleted }) => (
    <div
      className={`
        flex h-10 w-10 shrink-0 items-center justify-center rounded-full
        transition-colors duration-300 ease-in-out
        ${isCompleted ? 'bg-blue-500' : isActive ? 'border-2 border-blue-500 bg-white' : 'border-2 border-gray-200 bg-white'}
      `}
    >
      {isCompleted ? (
        <CheckMark />
      ) : (
        <span className={`text-sm font-medium ${isActive ? 'text-blue-500' : 'text-gray-500'}`}>
          {step.icon}
        </span>
      )}
    </div>
  );
  
  export default StepperDot;

// src/app/components/home/stepper/stepper-dot/stepper-dot.component.ts
import {Component, Input} from '@angular/core';
import {CommonModule} from '@angular/common';

@Component({
  selector: 'app-stepper-dot',
  imports: [CommonModule],
  standalone: true,
  templateUrl: './stepper-dot.component.html',
  styleUrl: './stepper-dot.component.css'
})
export class StepperDotComponent {
  @Input() step!: string | undefined;
  @Input() isActive: boolean = false;
  @Input() isCompleted: boolean = false;
}

<div
  class="
    flex h-10 w-10 shrink-0 items-center justify-center rounded-full
    transition-colors duration-300 ease-in-out
    {{ isCompleted ? 'bg-indigo-500' : isActive ? 'border-2 border-indigo-500 bg-white' : 'border-2 border-gray-200 bg-white' }}
  "
>
  <ng-container *ngIf="isCompleted; else stepIcon">
    <svg
      class="w-5 h-5 text-white"
      fill="none"
      stroke="currentColor"
      viewBox="0 0 24 24"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M5 13l4 4L19 7"
      />
    </svg>

  </ng-container>

  <ng-template #stepIcon>
    <span class="text-sm font-medium {{ isActive ? 'text-indigo-500' : 'text-gray-500' }}">
      {{ step }}
    </span>
  </ng-template>
</div>
