// src/app/components/home/stepper/stepper.component.ts
import {Component, Input} from '@angular/core';
import {CommonModule} from '@angular/common';
import {StepperDotComponent} from './stepper-dot/stepper-dot.component';
import {Step} from '../../../models/step';

@Component({
  selector: 'app-stepper',
  imports: [CommonModule, StepperDotComponent],
  standalone: true,
  templateUrl: './stepper.component.html',
  styleUrl: './stepper.component.css'
})
export class StepperComponent {
  @Input() steps: Step[] = [];
  @Input() currentStep: number = 1;
  @Input() layout: 'horizontal' | 'vertical' = 'horizontal';

  getProgress(): string {
    return `${((this.currentStep - 1) / (this.steps.length - 1)) * 100}%`;
  }

  isStepActive(index: number): boolean {
    return index + 1 === this.currentStep;
  }

  isStepCompleted(index: number): boolean {
    return index + 1 < this.currentStep;
  }
}

<div
  class="relative flex"
  [ngClass]="{
    'flex-col': layout === 'vertical',
    'flex-row justify-between w-full': layout === 'horizontal'
  }"
>
  <!-- Ligne de progression horizontale -->
  <div
    *ngIf="layout === 'horizontal'"
    class="absolute top-5 left-0 w-full h-0.5 bg-gray-200"
  >
    <div
      class="h-full bg-indigo-500 transition-all duration-300"
      [style.width]="getProgress()"
    ></div>
  </div>

  <!-- Étapes -->
  <div
    *ngFor="let step of steps; let index = index"
    class="relative flex z-10"
    [ngClass]="{
      'flex-row items-center': layout === 'vertical',
      'flex-col items-center': layout === 'horizontal',
      'mb-8 last:mb-0': layout === 'vertical'
    }"
  >
    <!-- Ligne de connexion verticale -->
    <div
      *ngIf="layout === 'vertical' && index < steps.length - 1"
      class="absolute left-5 top-10 w-0.5 h-16 -z-10 bg-gray-200"
    >
      <div
        class="w-full bg-indigo-500 transition-all duration-300"
        [style.height]="isStepCompleted(index) ? '100%' : '0%'"
      ></div>
    </div>

    <!-- Indicateur d'étape -->
    <app-stepper-dot
      [step]="step?.icon"
      [isActive]="isStepActive(index)"
      [isCompleted]="isStepCompleted(index)"
    ></app-stepper-dot>

    <!-- Libellé de l'étape -->
    <div
      class="min-w-[80px] text-center"
      [ngClass]="{ 'ml-4': layout === 'vertical', 'mt-2': layout === 'horizontal' }"
    >
      <span
        class="text-sm font-medium"
        [ngClass]="{
          'text-indigo-500': isStepActive(index) || isStepCompleted(index),
          'text-gray-500': !isStepActive(index) && !isStepCompleted(index)
        }"
      >
        {{ step.label }}
      </span>
    </div>
  </div>
</div>

// frontend/uml2code-frontend/src/components/stepper/Stepper.jsx
import StepperDot from "./StepperDot"

const Stepper = ({ steps, currentStep, layout }) => (
    <div className={`
      relative flex 
      ${layout === 'vertical' ? 'flex-col' : 'flex-row justify-between w-full'}
    `}>
      {/* Connection lines */}
      {layout === 'horizontal' && (
        <div className="absolute top-5 left-0 w-full h-0.5 bg-gray-200">
          <div 
            className="h-full bg-blue-500 transition-all duration-300"
            style={{ 
              width: `${((currentStep - 1) / (steps.length - 1)) * 100}%`
            }}
          />
        </div>
      )}
  
      {steps.map((step, index) => {
        const isActive = index + 1 === currentStep;
        const isCompleted = index + 1 < currentStep;
  
        return (
          <div
            key={index}
            className={`
              relative flex 
              ${layout === 'vertical' ? 'flex-row items-center' : 'flex-col items-center'}
              ${layout === 'vertical' ? 'mb-8 last:mb-0' : ''}
              z-10
            `}
          >
            {/* Vertical connection line */}
            {layout === 'vertical' && index < steps.length - 1 && (
              <div className="absolute left-5 top-10 w-0.5 h-16 -z-10">
                <div className="w-full h-full bg-gray-200">
                  <div 
                    className="w-full bg-blue-500 transition-all duration-300"
                    style={{ 
                      height: isCompleted ? '100%' : '0%'
                    }}
                  />
                </div>
              </div>
            )}
  
            <StepperDot 
              step={step}
              isActive={isActive}
              isCompleted={isCompleted}
            />
            
            {/* Step label */}
            <div className={`
              ${layout === 'vertical' ? 'ml-4' : 'mt-2'}
              min-w-[80px] text-center
            `}>
              <span className={`
                text-sm font-medium
                ${isActive ? 'text-blue-500' : isCompleted ? 'text-blue-500' : 'text-gray-500'}
              `}>
                {step.label}
              </span>
            </div>
          </div>
        );
      })}
    </div>
  );
  
  export default Stepper;
