// frontend/uml2code-frontend/src/components/stepper/ProgressBar.jsx
import Spinner from "../icons/Spinner";

const ProgressBar = ({ progress, isUploading, progressMessage }) => {
  if (!isUploading && progress === 0) return null; // Do not show when not uploading and no progress

  return (
    <div className="space-y-2">
      {isUploading && progress < 100 && (
        <div className="flex items-center gap-2 text-gray-500">
          <Spinner />
          <span className="text-sm">{progressMessage}</span>
        </div>
      )}
      <div className="w-full bg-gray-200 rounded-full h-2">
        <div 
          className="bg-blue-500 h-2 rounded-full transition-all duration-300"
          style={{ width: `${progress}%` }}
        />
      </div>
    </div>
  );
};

export default ProgressBar;

// src/app/components/home/progress-bar/progress-bar.component.ts
import {Component, Input} from '@angular/core';
import {SpinnerComponent} from './spinner/spinner.component';
import {CommonModule} from '@angular/common';

@Component({
  selector: 'app-progress-bar',
  standalone:true,
  imports: [
    SpinnerComponent,
    CommonModule
  ],
  templateUrl: './progress-bar.component.html',
  styleUrl: './progress-bar.component.css'
})
export class ProgressBarComponent {
  @Input() progress: number = 0;
  @Input() isUploading: boolean = false;
  @Input() progressMessage: string = '';
}

<div *ngIf="isUploading || progress > 0" class="space-y-2">
  <div *ngIf="isUploading && progress < 100" class="flex items-center gap-2 text-gray-500">
    <app-spinner></app-spinner>
    <span class="text-sm">{{ progressMessage }}</span>
  </div>
  <div class="w-full bg-gray-200 rounded-full h-2">
    <div
      class="bg-indigo-500 h-2 rounded-full transition-all duration-300"
      style="width: {{ progress }}%;">
    </div>
  </div>
</div>
